flea = true
allow_quest_locked = true
allow_fir_only = false
meta_only = false
roll_thermals = false

[trader_levels]
Prapor = 4
Therapist = 4
Skier = 4
Peacekeeper = 4
Mechanic = 4
Ragman = 4
Jaeger = 4
